import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { api } from '../../../services/api';
import { Colors, Radius, Spacing } from '../../../services/theme';
import ScreenHeader from '../../../components/ScreenHeader';

const statusLabel={planning:'Em planejamento',scheduled:'Agendada',confirmed:'Confirmada',performed:'Realizada',cancelled:'Cancelada',sent:'Aguardando assinatura',patient_signed:'Assinado pela paciente',completed:'Concluído',withdrawal_requested:'Revisão solicitada'};
export default function CirurgiaDetalhe(){
  const {id}=useLocalSearchParams(); const [item,setItem]=useState(null); const [error,setError]=useState(''); const [signing,setSigning]=useState(null); const [challenge,setChallenge]=useState(null); const [code,setCode]=useState('');
  const load=async()=>{try{setItem(await api(`/api/my-surgeries/${id}`));}catch(e){setError(e.message);}}; useEffect(()=>{load();},[id]);
  const requestCode=async consent=>{try{const result=await api(`/api/my-surgery-consents/${consent.id}/otp`,{method:'POST',body:JSON.stringify({channel:'whatsapp'})});setSigning(consent);setChallenge(result);Alert.alert('Código enviado',`Enviamos por ${result.channel==='whatsapp'?'WhatsApp':'e-mail'} para ${result.destination_masked}.`);}catch(e){Alert.alert('Código',e.message);}};
  const readTerm=async consent=>{try{const result=await api(`/api/my-surgery-consents/${consent.id}/pdf-url`);if(!result?.url)throw new Error('Termo indisponível.');await WebBrowser.openBrowserAsync(result.url,{toolbarColor:Colors.primary,controlsColor:'#fff'});}catch(e){Alert.alert('Termo',e.message);}};
  const sign=async()=>{try{await api(`/api/my-surgery-consents/${signing.id}/sign`,{method:'POST',body:JSON.stringify({challenge_id:challenge.challenge_id,code})});setSigning(null);setChallenge(null);setCode('');await load();Alert.alert('Termo assinado','Sua confirmação foi registrada.');}catch(e){Alert.alert('Assinatura',e.message);}};
  const withdraw=consent=>Alert.prompt('Solicitar revisão','Explique o motivo. A equipe receberá uma notificação.',async reason=>{if(!reason?.trim())return;try{await api(`/api/my-surgery-consents/${consent.id}/withdrawal`,{method:'POST',body:JSON.stringify({reason})});await load();}catch(e){Alert.alert('Revisão',e.message);}});
  if(error)return <View style={s.container}><ScreenHeader title="Cirurgia"/><Text style={s.error}>{error}</Text></View>; if(!item)return <View style={s.center}><ActivityIndicator color={Colors.primary}/></View>;
  return <View style={s.container}><ScreenHeader title="Detalhes da Cirurgia"/><ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.status}>{statusLabel[item.status]||item.status}</Text><Text style={s.title}>{item.procedure_name}</Text><Text style={s.line}><Ionicons name="calendar-outline"/> {item.scheduled_date?new Date(`${String(item.scheduled_date).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'Data a definir'} {item.scheduled_time?`às ${String(item.scheduled_time).slice(0,5)}`:''}</Text><Text style={s.line}>Dr(a). {item.doctor_name}</Text>{item.hospital_name?<Text style={s.line}>{item.hospital_name}</Text>:null}{item.gestational?.at_surgery?.label?<View style={s.ig}><Text style={s.igTitle}>IG prevista na cirurgia</Text><Text style={s.igValue}>{item.gestational.at_surgery.label}</Text></View>:null}</View>
    {item.patient_instructions?<Section title="Orientações"><Text style={s.body}>{item.patient_instructions}</Text></Section>:null}
    <Section title="Documentos">{(item.attachments||[]).length?(item.attachments||[]).map(file=><View key={file.id} style={s.document}><Ionicons name="document-text-outline" size={20} color={Colors.primary}/><Text style={{flex:1}}>{file.filename}</Text></View>):<Text style={s.muted}>Nenhum documento compartilhado.</Text>}</Section>
    <Section title="Termos e consentimentos">{(item.consents||[]).length?(item.consents||[]).map(consent=><View key={consent.id} style={s.consent}><View style={{flex:1}}><Text style={s.consentTitle}>{consent.template_name}</Text><Text style={s.muted}>{statusLabel[consent.status]||consent.status}</Text></View><Pressable onPress={()=>readTerm(consent)}><Text style={s.read}>Ler termo</Text></Pressable>{['sent','pending'].includes(consent.status)?<Pressable style={s.primaryBtn} onPress={()=>requestCode(consent)}><Text style={s.primaryText}>Assinar</Text></Pressable>:null}{['patient_signed','completed'].includes(consent.status)?<Pressable onPress={()=>withdraw(consent)}><Text style={s.withdraw}>Solicitar revisão</Text></Pressable>:null}</View>):<Text style={s.muted}>Nenhum termo pendente.</Text>}
      {signing?<View style={s.signBox}><Text style={s.consentTitle}>Digite o código de 6 dígitos</Text><TextInput style={s.code} value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="000000"/><Pressable style={[s.primaryBtn,code.length!==6&&{opacity:.5}]} disabled={code.length!==6} onPress={sign}><Text style={s.primaryText}>Confirmar assinatura</Text></Pressable><Text style={s.legal}>Ao confirmar, você declara que leu e concorda com o termo. O evento, horário, dispositivo e canal de validação serão registrados.</Text></View>:null}
    </Section>
  </ScrollView></View>;
}
function Section({title,children}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:Colors.bg},center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:Spacing.md,paddingBottom:50},hero:{backgroundColor:Colors.card,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:16},status:{color:Colors.primary,fontSize:12,fontWeight:'700',textTransform:'uppercase'},title:{fontSize:21,fontWeight:'800',color:Colors.text,marginVertical:8},line:{color:Colors.textSecondary,marginTop:5},ig:{backgroundColor:Colors.primarySofter,borderRadius:Radius.sm,padding:10,marginTop:14,flexDirection:'row',justifyContent:'space-between'},igTitle:{color:Colors.primary,fontWeight:'600'},igValue:{color:Colors.primary,fontWeight:'800'},section:{backgroundColor:Colors.card,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,padding:14,marginTop:12},sectionTitle:{fontSize:15,fontWeight:'800',color:Colors.text,marginBottom:10},body:{color:Colors.textSecondary,lineHeight:21},document:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:8,borderBottomWidth:1,borderColor:Colors.borderLight},consent:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:9,flexWrap:'wrap'},consentTitle:{fontWeight:'700',color:Colors.text},muted:{fontSize:12,color:Colors.textMuted},primaryBtn:{backgroundColor:Colors.primary,borderRadius:Radius.sm,paddingHorizontal:12,paddingVertical:9},primaryText:{color:'#fff',fontWeight:'700'},read:{color:Colors.primary,fontSize:12,fontWeight:'700'},withdraw:{color:Colors.warning,fontSize:12,fontWeight:'700'},signBox:{backgroundColor:Colors.primarySofter,borderRadius:Radius.sm,padding:12,marginTop:10,gap:10},code:{backgroundColor:'#fff',borderWidth:1,borderColor:Colors.border,borderRadius:Radius.sm,padding:12,fontSize:22,letterSpacing:8,textAlign:'center'},legal:{fontSize:11,color:Colors.textMuted,lineHeight:16},error:{margin:16,padding:12,color:Colors.danger,backgroundColor:Colors.dangerBg}});
